// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dots_server_v2.Data;

namespace dots_server_v2.Migrations
{
    [DbContext(typeof(DotsContext))]
    [Migration("20210824130437_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("dots_server_v2.Models.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("dots_server_v2.Models.AppPackage", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppId", "PackageId");

                    b.HasIndex("PackageName");

                    b.ToTable("AppPackages");
                });

            modelBuilder.Entity("dots_server_v2.Models.DotsUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dots_server_v2.Models.Package", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("InstallCount")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("dots_server_v2.Models.Screenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("PackageName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PackageName");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("dots_server_v2.Models.AppPackage", b =>
                {
                    b.HasOne("dots_server_v2.Models.App", "App")
                        .WithMany("AppPackages")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dots_server_v2.Models.Package", "Package")
                        .WithMany("AppsPackages")
                        .HasForeignKey("PackageName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("dots_server_v2.Models.Package", b =>
                {
                    b.HasOne("dots_server_v2.Models.DotsUser", "User")
                        .WithMany("Packages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dots_server_v2.Models.Screenshot", b =>
                {
                    b.HasOne("dots_server_v2.Models.Package", "Package")
                        .WithMany("Screenshots")
                        .HasForeignKey("PackageName");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("dots_server_v2.Models.App", b =>
                {
                    b.Navigation("AppPackages");
                });

            modelBuilder.Entity("dots_server_v2.Models.DotsUser", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("dots_server_v2.Models.Package", b =>
                {
                    b.Navigation("AppsPackages");

                    b.Navigation("Screenshots");
                });
#pragma warning restore 612, 618
        }
    }
}
